% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={STA 5207: Homework 5},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{STA 5207: Homework 5}
\author{}
\date{\vspace{-2.5em}Due: Friday, February 23 by 11:59 PM}

\begin{document}
\maketitle

Include your R code in an R chunks as part of your answer. In addition,
your written answer to each exercise should be self-contained so that
the grader can determine your solution without reading your code or
deciphering its output.

\hypertarget{exercise-1-using-step-40-points}{%
\subsection{\texorpdfstring{Exercise 1 (Using \texttt{step}) {[}40
points{]}}{Exercise 1 (Using step) {[}40 points{]}}}\label{exercise-1-using-step-40-points}}

For this exercise we will use the \texttt{prostate} data set from the
\texttt{faraway} package. You can also find the data in
\texttt{prostate.csv} on Canvas. The data set comes from a study on 97
men with prostate cancer who were due to receive a radical
prostatectomy. The variables in the data set are

\begin{itemize}
\tightlist
\item
  \texttt{lcavol}: \(\log(\text{cancer volume})\).
\item
  \texttt{lweight}: \(\log(\text{prostate weight})\).
\item
  \texttt{age}: The patient's age in years.
\item
  \texttt{lbph}: \(\log(\text{benign prostatic hyperplasia amount})\).
\item
  \texttt{svi}: Seminal vesicle invasion.
\item
  \texttt{lcp}: \(\log(\text{capsular penetration})\).
\item
  \texttt{gleason}: Gleason score.
\item
  \texttt{pgg45}: percentage Gleason score 4 or 5.
\item
  \texttt{lpsa}: \(\log(\text{prostate specific antigen})\).
\end{itemize}

In the following exercises, use \texttt{lpsa} as the response and the
other variables as predictors.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  (6 points) Identify the best model based on AIC and BIC using forward
  selection. Create a table listing each quality criterion (AIC, BIC)
  and the subset of variables chosen by the method.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(prostate, }\AttributeTok{package =} \StringTok{\textquotesingle{}faraway\textquotesingle{}}\NormalTok{)}
\NormalTok{mod\_start }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lpsa }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{, }\AttributeTok{data=}\NormalTok{prostate)}
\NormalTok{mod\_forwd\_aic }\OtherTok{\textless{}{-}} \FunctionTok{step}\NormalTok{(mod\_start, }\AttributeTok{scope=}\NormalTok{lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lcavol }\SpecialCharTok{+}\NormalTok{ lweight }\SpecialCharTok{+}\NormalTok{ age }\SpecialCharTok{+}\NormalTok{ lbph }\SpecialCharTok{+}\NormalTok{ svi }\SpecialCharTok{+}\NormalTok{ lcp }\SpecialCharTok{+}\NormalTok{ gleason }\SpecialCharTok{+}\NormalTok{ pgg45, }\AttributeTok{direction =} \StringTok{\textquotesingle{}forward\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=28.84
## lpsa ~ 1
## 
##           Df Sum of Sq     RSS     AIC
## + lcavol   1    69.003  58.915 -44.366
## + svi      1    41.011  86.907  -6.658
## + lcp      1    38.528  89.389  -3.926
## + pgg45    1    22.814 105.103  11.783
## + gleason  1    17.416 110.501  16.641
## + lweight  1    16.041 111.876  17.840
## + lbph     1     4.136 123.782  27.650
## + age      1     3.679 124.238  28.007
## <none>                 127.918  28.837
## 
## Step:  AIC=-44.37
## lpsa ~ lcavol
## 
##           Df Sum of Sq    RSS     AIC
## + lweight  1    5.9485 52.966 -52.690
## + svi      1    5.2375 53.677 -51.397
## + lbph     1    3.2658 55.649 -47.898
## + pgg45    1    1.6980 57.217 -45.203
## <none>                 58.915 -44.366
## + lcp      1    0.6562 58.259 -43.453
## + gleason  1    0.4156 58.499 -43.053
## + age      1    0.0025 58.912 -42.370
## 
## Step:  AIC=-52.69
## lpsa ~ lcavol + lweight
## 
##           Df Sum of Sq    RSS     AIC
## + svi      1    5.1814 47.785 -60.676
## + pgg45    1    1.9489 51.017 -54.327
## <none>                 52.966 -52.690
## + lcp      1    0.8371 52.129 -52.236
## + gleason  1    0.7810 52.185 -52.131
## + lbph     1    0.6751 52.291 -51.935
## + age      1    0.4200 52.546 -51.463
## 
## Step:  AIC=-60.68
## lpsa ~ lcavol + lweight + svi
## 
##           Df Sum of Sq    RSS     AIC
## + lbph     1   1.30006 46.485 -61.352
## <none>                 47.785 -60.676
## + pgg45    1   0.57347 47.211 -59.847
## + age      1   0.40251 47.382 -59.497
## + gleason  1   0.38901 47.396 -59.469
## + lcp      1   0.06412 47.721 -58.806
## 
## Step:  AIC=-61.35
## lpsa ~ lcavol + lweight + svi + lbph
## 
##           Df Sum of Sq    RSS     AIC
## + age      1   0.95924 45.526 -61.374
## <none>                 46.485 -61.352
## + pgg45    1   0.35332 46.131 -60.092
## + gleason  1   0.21256 46.272 -59.796
## + lcp      1   0.10230 46.383 -59.565
## 
## Step:  AIC=-61.37
## lpsa ~ lcavol + lweight + svi + lbph + age
## 
##           Df Sum of Sq    RSS     AIC
## <none>                 45.526 -61.374
## + pgg45    1   0.65896 44.867 -60.789
## + gleason  1   0.45601 45.070 -60.351
## + lcp      1   0.12927 45.396 -59.650
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(prostate)}
\NormalTok{mod\_forwd\_bic }\OtherTok{\textless{}{-}} \FunctionTok{step}\NormalTok{(mod\_start, }\AttributeTok{scope=}\NormalTok{lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lcavol }\SpecialCharTok{+}\NormalTok{ lweight }\SpecialCharTok{+}\NormalTok{ age }\SpecialCharTok{+}\NormalTok{ lbph }\SpecialCharTok{+}\NormalTok{ svi }\SpecialCharTok{+}\NormalTok{ lcp }\SpecialCharTok{+}\NormalTok{ gleason }\SpecialCharTok{+}\NormalTok{ pgg45, }\AttributeTok{direction =} \StringTok{\textquotesingle{}forward\textquotesingle{}}\NormalTok{, }\AttributeTok{k=}\FunctionTok{log}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=31.41
## lpsa ~ 1
## 
##           Df Sum of Sq     RSS     AIC
## + lcavol   1    69.003  58.915 -39.217
## + svi      1    41.011  86.907  -1.508
## + lcp      1    38.528  89.389   1.224
## + pgg45    1    22.814 105.103  16.932
## + gleason  1    17.416 110.501  21.790
## + lweight  1    16.041 111.876  22.990
## <none>                 127.918  31.412
## + lbph     1     4.136 123.782  32.799
## + age      1     3.679 124.238  33.156
## 
## Step:  AIC=-39.22
## lpsa ~ lcavol
## 
##           Df Sum of Sq    RSS     AIC
## + lweight  1    5.9485 52.966 -44.966
## + svi      1    5.2375 53.677 -43.673
## + lbph     1    3.2658 55.649 -40.174
## <none>                 58.915 -39.217
## + pgg45    1    1.6980 57.217 -37.479
## + lcp      1    0.6562 58.259 -35.728
## + gleason  1    0.4156 58.499 -35.329
## + age      1    0.0025 58.912 -34.646
## 
## Step:  AIC=-44.97
## lpsa ~ lcavol + lweight
## 
##           Df Sum of Sq    RSS     AIC
## + svi      1    5.1814 47.785 -50.377
## <none>                 52.966 -44.966
## + pgg45    1    1.9489 51.017 -44.028
## + lcp      1    0.8371 52.129 -41.937
## + gleason  1    0.7810 52.185 -41.833
## + lbph     1    0.6751 52.291 -41.636
## + age      1    0.4200 52.546 -41.164
## 
## Step:  AIC=-50.38
## lpsa ~ lcavol + lweight + svi
## 
##           Df Sum of Sq    RSS     AIC
## <none>                 47.785 -50.377
## + lbph     1   1.30006 46.485 -48.478
## + pgg45    1   0.57347 47.211 -46.974
## + age      1   0.40251 47.382 -46.623
## + gleason  1   0.38901 47.396 -46.596
## + lcp      1   0.06412 47.721 -45.933
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{coef}\NormalTok{(mod\_forwd\_aic))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      lcavol     lweight         svi        lbph         age 
##  0.95099742  0.56560801  0.42369200  0.72095499  0.11183992 -0.01489225
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{coef}\NormalTok{(mod\_forwd\_bic))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      lcavol     lweight         svi 
##  -0.2680926   0.5516380   0.5085413   0.6661584
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{quality\_criterion }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}AIC\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}BIC\textquotesingle{}}\NormalTok{)}
\NormalTok{variables }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}lcavol,lweight,svi,lbph,age\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}lcavol,lweight,svi\textquotesingle{}}\NormalTok{)}
\NormalTok{criterion\_values }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{extractAIC}\NormalTok{(mod\_forwd\_aic)[}\DecValTok{2}\NormalTok{], }\FunctionTok{extractAIC}\NormalTok{(mod\_forwd\_bic, }\AttributeTok{k=}\FunctionTok{log}\NormalTok{(n))[}\DecValTok{2}\NormalTok{])}
\FunctionTok{data.frame}\NormalTok{(quality\_criterion, variables, criterion\_values)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   quality_criterion                   variables criterion_values
## 1               AIC lcavol,lweight,svi,lbph,age        -61.37439
## 2               BIC          lcavol,lweight,svi        -50.37736
\end{verbatim}

  \textbf{Answer:} The best model using forward selection based on AIC
  was the model with predictors ``lcavol'', ``lweight'', ``svi'',
  ``lbph'', and ``age'' with a final AIC of -61.37439. The best model
  using forward selection based on BIC was the model with predictors
  ``lcavol'', ``lweight'', and ``svi'' with a final AIC of -50.37736.
  The table above shows the quality criterion used, variables selected,
  and the criterion values of each model.
\item
  (6 points) Identify the best model based on AIC and BIC using backward
  selection. Create a table listing each quality criterion (AIC, BIC)
  and the subset of variables chosen by the method.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod\_all\_preds }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data=}\NormalTok{prostate)}
\NormalTok{mod\_back\_aic }\OtherTok{\textless{}{-}} \FunctionTok{step}\NormalTok{(mod\_all\_preds, }\AttributeTok{direction =} \StringTok{\textquotesingle{}backward\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=-58.32
## lpsa ~ lcavol + lweight + age + lbph + svi + lcp + gleason + 
##     pgg45
## 
##           Df Sum of Sq    RSS     AIC
## - gleason  1    0.0412 44.204 -60.231
## - pgg45    1    0.5258 44.689 -59.174
## - lcp      1    0.6740 44.837 -58.853
## <none>                 44.163 -58.322
## - age      1    1.5503 45.713 -56.975
## - lbph     1    1.6835 45.847 -56.693
## - lweight  1    3.5861 47.749 -52.749
## - svi      1    4.9355 49.099 -50.046
## - lcavol   1   22.3721 66.535 -20.567
## 
## Step:  AIC=-60.23
## lpsa ~ lcavol + lweight + age + lbph + svi + lcp + pgg45
## 
##           Df Sum of Sq    RSS     AIC
## - lcp      1    0.6623 44.867 -60.789
## <none>                 44.204 -60.231
## - pgg45    1    1.1920 45.396 -59.650
## - age      1    1.5166 45.721 -58.959
## - lbph     1    1.7053 45.910 -58.560
## - lweight  1    3.5462 47.750 -54.746
## - svi      1    4.8984 49.103 -52.037
## - lcavol   1   23.5039 67.708 -20.872
## 
## Step:  AIC=-60.79
## lpsa ~ lcavol + lweight + age + lbph + svi + pgg45
## 
##           Df Sum of Sq    RSS     AIC
## - pgg45    1    0.6590 45.526 -61.374
## <none>                 44.867 -60.789
## - age      1    1.2649 46.131 -60.092
## - lbph     1    1.6465 46.513 -59.293
## - lweight  1    3.5647 48.431 -55.373
## - svi      1    4.2503 49.117 -54.009
## - lcavol   1   25.4189 70.285 -19.248
## 
## Step:  AIC=-61.37
## lpsa ~ lcavol + lweight + age + lbph + svi
## 
##           Df Sum of Sq    RSS     AIC
## <none>                 45.526 -61.374
## - age      1    0.9592 46.485 -61.352
## - lbph     1    1.8568 47.382 -59.497
## - lweight  1    3.2251 48.751 -56.735
## - svi      1    5.9517 51.477 -51.456
## - lcavol   1   28.7665 74.292 -15.871
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(prostate)}
\NormalTok{mod\_back\_bic }\OtherTok{\textless{}{-}} \FunctionTok{step}\NormalTok{(mod\_all\_preds, }\AttributeTok{direction =} \StringTok{\textquotesingle{}backward\textquotesingle{}}\NormalTok{, }\AttributeTok{k=}\FunctionTok{log}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=-35.15
## lpsa ~ lcavol + lweight + age + lbph + svi + lcp + gleason + 
##     pgg45
## 
##           Df Sum of Sq    RSS     AIC
## - gleason  1    0.0412 44.204 -39.634
## - pgg45    1    0.5258 44.689 -38.576
## - lcp      1    0.6740 44.837 -38.255
## - age      1    1.5503 45.713 -36.377
## - lbph     1    1.6835 45.847 -36.095
## <none>                 44.163 -35.149
## - lweight  1    3.5861 47.749 -32.151
## - svi      1    4.9355 49.099 -29.448
## - lcavol   1   22.3721 66.535   0.030
## 
## Step:  AIC=-39.63
## lpsa ~ lcavol + lweight + age + lbph + svi + lcp + pgg45
## 
##           Df Sum of Sq    RSS     AIC
## - lcp      1    0.6623 44.867 -42.766
## - pgg45    1    1.1920 45.396 -41.627
## - age      1    1.5166 45.721 -40.936
## - lbph     1    1.7053 45.910 -40.537
## <none>                 44.204 -39.634
## - lweight  1    3.5462 47.750 -36.723
## - svi      1    4.8984 49.103 -34.014
## - lcavol   1   23.5039 67.708  -2.849
## 
## Step:  AIC=-42.77
## lpsa ~ lcavol + lweight + age + lbph + svi + pgg45
## 
##           Df Sum of Sq    RSS     AIC
## - pgg45    1    0.6590 45.526 -45.926
## - age      1    1.2649 46.131 -44.644
## - lbph     1    1.6465 46.513 -43.844
## <none>                 44.867 -42.766
## - lweight  1    3.5647 48.431 -39.925
## - svi      1    4.2503 49.117 -38.561
## - lcavol   1   25.4189 70.285  -3.800
## 
## Step:  AIC=-45.93
## lpsa ~ lcavol + lweight + age + lbph + svi
## 
##           Df Sum of Sq    RSS     AIC
## - age      1    0.9592 46.485 -48.478
## - lbph     1    1.8568 47.382 -46.623
## <none>                 45.526 -45.926
## - lweight  1    3.2251 48.751 -43.862
## - svi      1    5.9517 51.477 -38.583
## - lcavol   1   28.7665 74.292  -2.997
## 
## Step:  AIC=-48.48
## lpsa ~ lcavol + lweight + lbph + svi
## 
##           Df Sum of Sq    RSS     AIC
## - lbph     1    1.3001 47.785 -50.377
## <none>                 46.485 -48.478
## - lweight  1    2.8014 49.286 -47.377
## - svi      1    5.8063 52.291 -41.636
## - lcavol   1   27.8298 74.315  -7.542
## 
## Step:  AIC=-50.38
## lpsa ~ lcavol + lweight + svi
## 
##           Df Sum of Sq    RSS     AIC
## <none>                 47.785 -50.377
## - svi      1    5.1814 52.966 -44.966
## - lweight  1    5.8924 53.677 -43.673
## - lcavol   1   28.0445 75.829 -10.160
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{coef}\NormalTok{(mod\_back\_aic))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      lcavol     lweight         age        lbph         svi 
##  0.95099742  0.56560801  0.42369200 -0.01489225  0.11183992  0.72095499
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{coef}\NormalTok{(mod\_back\_bic))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      lcavol     lweight         svi 
##  -0.2680926   0.5516380   0.5085413   0.6661584
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{quality\_criterion }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}AIC\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}BIC\textquotesingle{}}\NormalTok{)}
\NormalTok{variables }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}lcavol,lweight,svi,lbph,age\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}lcavol,lweight,svi\textquotesingle{}}\NormalTok{)}
\NormalTok{criterion\_values }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{extractAIC}\NormalTok{(mod\_back\_aic)[}\DecValTok{2}\NormalTok{], }\FunctionTok{extractAIC}\NormalTok{(mod\_back\_bic, }\AttributeTok{k=}\FunctionTok{log}\NormalTok{(n))[}\DecValTok{2}\NormalTok{])}
\FunctionTok{data.frame}\NormalTok{(quality\_criterion, variables, criterion\_values)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   quality_criterion                   variables criterion_values
## 1               AIC lcavol,lweight,svi,lbph,age        -61.37439
## 2               BIC          lcavol,lweight,svi        -50.37736
\end{verbatim}

  \textbf{Answer:} The best model using backward selection based on AIC
  was the model with predictors ``lcavol'', ``lweight'', ``svi'',
  ``lbph'', and ``age'' with a final AIC of -61.37439. The best model
  using backward selection based on BIC was the model with predictors
  ``lcavol'', ``lweight'', and ``svi'' with a final AIC of -50.37736.
  The table above shows the quality criterion used, variables selected,
  and the criterion values of each model.
\item
  (6 points) Identify the best model based on AIC and BIC using stepwise
  selection. Create a table listing each quality criterion (AIC, BIC)
  and the subset of variables chosen by the method.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod\_start }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lpsa }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{, }\AttributeTok{data=}\NormalTok{prostate)}
\NormalTok{mod\_stepwise\_aic }\OtherTok{\textless{}{-}} \FunctionTok{step}\NormalTok{(mod\_start, }\AttributeTok{scope=}\NormalTok{lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lcavol }\SpecialCharTok{+}\NormalTok{ lweight }\SpecialCharTok{+}\NormalTok{ age }\SpecialCharTok{+}\NormalTok{ lbph }\SpecialCharTok{+}\NormalTok{ svi }\SpecialCharTok{+}\NormalTok{ lcp }\SpecialCharTok{+}\NormalTok{ gleason }\SpecialCharTok{+}\NormalTok{ pgg45, }\AttributeTok{direction =} \StringTok{\textquotesingle{}both\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=28.84
## lpsa ~ 1
## 
##           Df Sum of Sq     RSS     AIC
## + lcavol   1    69.003  58.915 -44.366
## + svi      1    41.011  86.907  -6.658
## + lcp      1    38.528  89.389  -3.926
## + pgg45    1    22.814 105.103  11.783
## + gleason  1    17.416 110.501  16.641
## + lweight  1    16.041 111.876  17.840
## + lbph     1     4.136 123.782  27.650
## + age      1     3.679 124.238  28.007
## <none>                 127.918  28.837
## 
## Step:  AIC=-44.37
## lpsa ~ lcavol
## 
##           Df Sum of Sq     RSS     AIC
## + lweight  1     5.949  52.966 -52.690
## + svi      1     5.237  53.677 -51.397
## + lbph     1     3.266  55.649 -47.898
## + pgg45    1     1.698  57.217 -45.203
## <none>                  58.915 -44.366
## + lcp      1     0.656  58.259 -43.453
## + gleason  1     0.416  58.499 -43.053
## + age      1     0.003  58.912 -42.370
## - lcavol   1    69.003 127.918  28.837
## 
## Step:  AIC=-52.69
## lpsa ~ lcavol + lweight
## 
##           Df Sum of Sq     RSS     AIC
## + svi      1     5.181  47.785 -60.676
## + pgg45    1     1.949  51.017 -54.327
## <none>                  52.966 -52.690
## + lcp      1     0.837  52.129 -52.236
## + gleason  1     0.781  52.185 -52.131
## + lbph     1     0.675  52.291 -51.935
## + age      1     0.420  52.546 -51.463
## - lweight  1     5.949  58.915 -44.366
## - lcavol   1    58.910 111.876  17.840
## 
## Step:  AIC=-60.68
## lpsa ~ lcavol + lweight + svi
## 
##           Df Sum of Sq    RSS     AIC
## + lbph     1    1.3001 46.485 -61.352
## <none>                 47.785 -60.676
## + pgg45    1    0.5735 47.211 -59.847
## + age      1    0.4025 47.382 -59.497
## + gleason  1    0.3890 47.396 -59.469
## + lcp      1    0.0641 47.721 -58.806
## - svi      1    5.1814 52.966 -52.690
## - lweight  1    5.8924 53.677 -51.397
## - lcavol   1   28.0445 75.829 -17.884
## 
## Step:  AIC=-61.35
## lpsa ~ lcavol + lweight + svi + lbph
## 
##           Df Sum of Sq    RSS     AIC
## + age      1    0.9592 45.526 -61.374
## <none>                 46.485 -61.352
## - lbph     1    1.3001 47.785 -60.676
## + pgg45    1    0.3533 46.131 -60.092
## + gleason  1    0.2126 46.272 -59.796
## + lcp      1    0.1023 46.383 -59.565
## - lweight  1    2.8014 49.286 -57.676
## - svi      1    5.8063 52.291 -51.935
## - lcavol   1   27.8298 74.315 -17.841
## 
## Step:  AIC=-61.37
## lpsa ~ lcavol + lweight + svi + lbph + age
## 
##           Df Sum of Sq    RSS     AIC
## <none>                 45.526 -61.374
## - age      1    0.9592 46.485 -61.352
## + pgg45    1    0.6590 44.867 -60.789
## + gleason  1    0.4560 45.070 -60.351
## + lcp      1    0.1293 45.396 -59.650
## - lbph     1    1.8568 47.382 -59.497
## - lweight  1    3.2251 48.751 -56.735
## - svi      1    5.9517 51.477 -51.456
## - lcavol   1   28.7665 74.292 -15.871
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(prostate)}
\NormalTok{mod\_stepwise\_bic }\OtherTok{\textless{}{-}} \FunctionTok{step}\NormalTok{(mod\_start, }\AttributeTok{scope=}\NormalTok{lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lcavol }\SpecialCharTok{+}\NormalTok{ lweight }\SpecialCharTok{+}\NormalTok{ age }\SpecialCharTok{+}\NormalTok{ lbph }\SpecialCharTok{+}\NormalTok{ svi }\SpecialCharTok{+}\NormalTok{ lcp }\SpecialCharTok{+}\NormalTok{ gleason }\SpecialCharTok{+}\NormalTok{ pgg45, }\AttributeTok{direction =} \StringTok{\textquotesingle{}both\textquotesingle{}}\NormalTok{, }\AttributeTok{k=}\FunctionTok{log}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=31.41
## lpsa ~ 1
## 
##           Df Sum of Sq     RSS     AIC
## + lcavol   1    69.003  58.915 -39.217
## + svi      1    41.011  86.907  -1.508
## + lcp      1    38.528  89.389   1.224
## + pgg45    1    22.814 105.103  16.932
## + gleason  1    17.416 110.501  21.790
## + lweight  1    16.041 111.876  22.990
## <none>                 127.918  31.412
## + lbph     1     4.136 123.782  32.799
## + age      1     3.679 124.238  33.156
## 
## Step:  AIC=-39.22
## lpsa ~ lcavol
## 
##           Df Sum of Sq     RSS     AIC
## + lweight  1     5.949  52.966 -44.966
## + svi      1     5.237  53.677 -43.673
## + lbph     1     3.266  55.649 -40.174
## <none>                  58.915 -39.217
## + pgg45    1     1.698  57.217 -37.479
## + lcp      1     0.656  58.259 -35.728
## + gleason  1     0.416  58.499 -35.329
## + age      1     0.003  58.912 -34.646
## - lcavol   1    69.003 127.918  31.412
## 
## Step:  AIC=-44.97
## lpsa ~ lcavol + lweight
## 
##           Df Sum of Sq     RSS     AIC
## + svi      1     5.181  47.785 -50.377
## <none>                  52.966 -44.966
## + pgg45    1     1.949  51.017 -44.028
## + lcp      1     0.837  52.129 -41.937
## + gleason  1     0.781  52.185 -41.833
## + lbph     1     0.675  52.291 -41.636
## + age      1     0.420  52.546 -41.164
## - lweight  1     5.949  58.915 -39.217
## - lcavol   1    58.910 111.876  22.990
## 
## Step:  AIC=-50.38
## lpsa ~ lcavol + lweight + svi
## 
##           Df Sum of Sq    RSS     AIC
## <none>                 47.785 -50.377
## + lbph     1    1.3001 46.485 -48.478
## + pgg45    1    0.5735 47.211 -46.974
## + age      1    0.4025 47.382 -46.623
## + gleason  1    0.3890 47.396 -46.596
## + lcp      1    0.0641 47.721 -45.933
## - svi      1    5.1814 52.966 -44.966
## - lweight  1    5.8924 53.677 -43.673
## - lcavol   1   28.0445 75.829 -10.160
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{coef}\NormalTok{(mod\_stepwise\_aic))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      lcavol     lweight         svi        lbph         age 
##  0.95099742  0.56560801  0.42369200  0.72095499  0.11183992 -0.01489225
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{coef}\NormalTok{(mod\_stepwise\_bic))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      lcavol     lweight         svi 
##  -0.2680926   0.5516380   0.5085413   0.6661584
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{quality\_criterion }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}AIC\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}BIC\textquotesingle{}}\NormalTok{)}
\NormalTok{variables }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}lcavol,lweight,svi,lbph,age\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}lcavol,lweight,svi\textquotesingle{}}\NormalTok{)}
\NormalTok{criterion\_values }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{extractAIC}\NormalTok{(mod\_stepwise\_aic)[}\DecValTok{2}\NormalTok{], }\FunctionTok{extractAIC}\NormalTok{(mod\_stepwise\_bic, }\AttributeTok{k=}\FunctionTok{log}\NormalTok{(n))[}\DecValTok{2}\NormalTok{])}
\FunctionTok{data.frame}\NormalTok{(quality\_criterion, variables, criterion\_values)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   quality_criterion                   variables criterion_values
## 1               AIC lcavol,lweight,svi,lbph,age        -61.37439
## 2               BIC          lcavol,lweight,svi        -50.37736
\end{verbatim}

  \textbf{Answer:} The best model using stepwise selection based on AIC
  was the model with predictors ``lcavol'', ``lweight'', ``svi'',
  ``lbph'', and ``age'' with a final AIC of -61.37439. The best model
  using stepwise selection based on BIC was the model with predictors
  ``lcavol'', ``lweight'', and ``svi'' with a final AIC of -50.37736.
  The table above shows the quality criterion used, variables selected,
  and the criterion values of each model.
\item
  (12 points) Identify the best model based on \(R_a^2\), AIC, and BIC
  using best subset selection. Create a table listing each quality
  criterion (\(R_a^2\), AIC, BIC) and the subset of variables chosen by
  the method.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(leaps)}
\NormalTok{mod\_exhaustive }\OtherTok{=} \FunctionTok{summary}\NormalTok{(}\FunctionTok{regsubsets}\NormalTok{(lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data=}\NormalTok{prostate, }\AttributeTok{nvmax =} \DecValTok{8}\NormalTok{))}
\NormalTok{bestr2 }\OtherTok{\textless{}{-}}\NormalTok{ mod\_exhaustive}\SpecialCharTok{$}\NormalTok{which[}\FunctionTok{which.max}\NormalTok{(mod\_exhaustive}\SpecialCharTok{$}\NormalTok{adjr2),]}
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(mod\_exhaustive}\SpecialCharTok{$}\NormalTok{which)}
\NormalTok{mod\_aic }\OtherTok{\textless{}{-}}\NormalTok{ n }\SpecialCharTok{*} \FunctionTok{log}\NormalTok{(mod\_exhaustive}\SpecialCharTok{$}\NormalTok{rss }\SpecialCharTok{/}\NormalTok{ n) }\SpecialCharTok{+} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ (}\DecValTok{2}\SpecialCharTok{:}\NormalTok{p)}
\NormalTok{mod\_bic }\OtherTok{\textless{}{-}}\NormalTok{ n }\SpecialCharTok{*} \FunctionTok{log}\NormalTok{(mod\_exhaustive}\SpecialCharTok{$}\NormalTok{rss }\SpecialCharTok{/}\NormalTok{ n) }\SpecialCharTok{+} \FunctionTok{log}\NormalTok{(n) }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{2}\SpecialCharTok{:}\NormalTok{p)}
\NormalTok{bestaic }\OtherTok{\textless{}{-}}\NormalTok{ mod\_exhaustive}\SpecialCharTok{$}\NormalTok{which[}\FunctionTok{which.min}\NormalTok{(mod\_aic),]}
\NormalTok{bestbic }\OtherTok{\textless{}{-}}\NormalTok{ mod\_exhaustive}\SpecialCharTok{$}\NormalTok{which[}\FunctionTok{which.min}\NormalTok{(mod\_bic),]}
\NormalTok{quality\_criterion }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}R2\_a\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}AIC\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}BIC\textquotesingle{}}\NormalTok{)}
\NormalTok{variables\_chosen }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}lcavol, lweight, age, lbph, svi, lcp, pgg45\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}lcavol, lweight, age, lbph, svi\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}lcavol, lweight, svi\textquotesingle{}}\NormalTok{)}
\NormalTok{criterion\_values }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{max}\NormalTok{(mod\_exhaustive}\SpecialCharTok{$}\NormalTok{adjr2), }\FunctionTok{min}\NormalTok{(mod\_aic), }\FunctionTok{min}\NormalTok{(mod\_bic))}
\FunctionTok{data.frame}\NormalTok{(quality\_criterion, variables\_chosen, criterion\_values)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   quality_criterion                            variables_chosen
## 1              R2_a lcavol, lweight, age, lbph, svi, lcp, pgg45
## 2               AIC             lcavol, lweight, age, lbph, svi
## 3               BIC                        lcavol, lweight, svi
##   criterion_values
## 1        0.6272521
## 2      -61.3743920
## 3      -50.3773618
\end{verbatim}

  \textbf{Answer:} Using best subset selection, the best model based on
  \(R^2_a\) is the model with predictors ``lcavol'', ``lweight'',
  ``age'', ``lbph'', ``svi'', ``lcp'', and ``pgg45''. Using best subset
  selection, the best model based on AIC is the model with predictors
  ``lcavol'', ``lweight'', ``age'', ``lbph'', and ``svi''. Using best
  subset selection, the best model based on BIC is the model with
  predictors ``lcavol'', ``lweight'', and ``svi''.
\item
  (10 points) For each unique candidate model chosen in parts 1 - 4,
  report their \(\text{RMSE}_{\text{LOOCV}}\). Which model do you prefer
  based on this criteria?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{calc\_loocv\_rmse }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model) \{}
  \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{((}\FunctionTok{resid}\NormalTok{(model) }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{hatvalues}\NormalTok{(model))) }\SpecialCharTok{\^{}} \DecValTok{2}\NormalTok{))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

  \textbf{Answer:}
\end{enumerate}

\hypertarget{exercise-2-boston-housing-data-40-points}{%
\subsection{\texorpdfstring{Exercise 2 (\texttt{Boston} Housing Data)
{[}40
points{]}}{Exercise 2 (Boston Housing Data) {[}40 points{]}}}\label{exercise-2-boston-housing-data-40-points}}

For this exercise we will use the \texttt{Boston} data set from the
\texttt{ISLR2} package. You can also find the data in
\texttt{Boston.csv} on Canvas. The data set contains housing values in
506 suburbs of Boston. There are a total of 12 predictors. You can type
\texttt{?ISLR2::Boston} in \texttt{R} to read about the data set and the
meaning of the predictors. In the following exercises, use \texttt{crim}
(the per capita crime rate) as the response and the other variables as
predictors.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  (6 points) Identify the best model based on AIC and BIC using forward
  selection. Create a table listing each quality criterion (AIC, BIC)
  and the subset of variables chosen by the method.
\item
  (6 points) Identify the best model based on AIC and BIC using backward
  selection. Create a table listing each quality criterion (AIC, BIC)
  and the subset of variables chosen by the method.
\item
  (6 points) Identify the best model based on AIC and BIC using stepwise
  selection. Create a table listing each quality criterion (AIC, BIC)
  and the subset of variables chosen by the method.
\item
  (12 points) Identify the best model based on \(R_a^2\), AIC, and BIC
  using best subset selection. Note that you have to set
  \texttt{nvmax\ =\ 12} when calling \texttt{regsubsets}, since there
  are 12 predictors. Create a table listing each quality criterion
  (\(R_a^2\), AIC, and BIC) and the subset of the variables chosen by
  the method.
\item
  (10 points) For each unique candidate model chosen in parts 1 - 4,
  report their \(\text{RMSE}_{\text{LOOCV}}\). Which model do you prefer
  based on this criteria?
\end{enumerate}

\hypertarget{exercise-3-post-selection-inference-and-data-splitting-20-points}{%
\subsection{Exercise 3 (Post-Selection Inference and Data Splitting)
{[}20
points{]}}\label{exercise-3-post-selection-inference-and-data-splitting-20-points}}

For this exercise, we will use the \texttt{prostate\_fake\_train.csv}
and \texttt{prostate\_fake\_test.csv} data sets on Canvas. These data
sets are subsets of the \texttt{prostate} data set you analyzed in
Exercise 1; however, I replaced the \texttt{lpsa} column with a column
of noise drawn from a uniform distribution on \([-1, 1]\). I then split
the data set into a training subset and a testing subset. I ran the
following code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}

\FunctionTok{data}\NormalTok{(prostate, }\AttributeTok{package =} \StringTok{\textquotesingle{}faraway\textquotesingle{}}\NormalTok{)}

\CommentTok{\# set random seed for reproducability}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123456}\NormalTok{)}

\CommentTok{\# replace the lpsa column with pure noise}
\NormalTok{prostate\_fake }\OtherTok{=}\NormalTok{ prostate }\SpecialCharTok{|\textgreater{}} 
    \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{lpsa) }\SpecialCharTok{|\textgreater{}} 
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{noise =} \FunctionTok{runif}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(prostate), }\AttributeTok{min =} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\AttributeTok{max =} \DecValTok{1}\NormalTok{))}

\CommentTok{\# train/test split}
\NormalTok{n }\OtherTok{=} \FunctionTok{nrow}\NormalTok{(prostate)}
\NormalTok{train }\OtherTok{=} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n, }\AttributeTok{size =} \DecValTok{49}\NormalTok{)}
\NormalTok{test }\OtherTok{=} \SpecialCharTok{!}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n }\SpecialCharTok{\%in\%}\NormalTok{ train)}

\CommentTok{\# write data to a file}
\FunctionTok{write\_csv}\NormalTok{(prostate\_fake[train,], }\StringTok{\textquotesingle{}prostate\_fake\_train.csv\textquotesingle{}}\NormalTok{)}
\FunctionTok{write\_csv}\NormalTok{(prostate\_fake[test,], }\StringTok{\textquotesingle{}prostate\_fake\_test.csv\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

For this exercise, use \texttt{noise} as the response and the remaining
variables as predictors. Note that by design there is no relationship
between \texttt{noise} and any of the predictors.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  (6 points) Identify the best model using AIC and backward selection
  based on the data in \texttt{prostate\_fake\_train.csv}. Report the
  subset of the variables chosen by this method.
\item
  (7 points) Using your model from part 1, perform a \(t\)-test at the
  \(\alpha = 0.05\) significance level for each predictor. Report the
  predictors that are significant according to this test. Should we
  trust the results of this test? Why or why not?
\item
  (7 points) Using the predictors you selected in part 1, fit a multiple
  linear regression model on the data in
  \texttt{prostate\_fake\_test.csv}. Perform a \(t\)-test at the
  \(\alpha = 0.05\) significance level for each predictor. Report the
  predictors that are significant according to this test. Do the results
  match the results from part 2? Should we trust these results? Why or
  why not?
\end{enumerate}

\end{document}
